### ISSUE TITLE
Support rendering of vertical wells

### ISSUE THREAD

**Issue by thuve** [equinor/esv-intersection#230] opened 2020-05-04 06:42 UTC
Exploration wells tend to be vertical. During planning the wellpath from compass will therefore be perfectly vertical (no difference in azimuth, northing/easting). 

The intersection component will need to support rendering of a vertical wellpath with displacement of 0m.

**Comment by andreabrambilla** [comment] 2020-05-05 11:13
duplicate of #226

**Closed by andreabrambilla** 2020-05-05 11:13 UTC
